# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sektoraler Heilpraktiker Physiotherapie - Fortbildung und Prüfung
fbtitle: Werde jetzt Heilpraktiker für Physiotherapie
fbimage: "https://heilpraktiker-physiotherapie.com/assets/images/FacebookErfolgreichAlsHPPT.jpg"
email: info@heilpraktiker-physiotherapie.com    
description: Heilpraktiker Physiotherapie - Fortbildung inklusive Prüfung zur Anerkennung nach Aktenlage, in NRW, Niedersachsen, Rheinland-Pfalz, Hessen, Baden-Württemberg, Bayern und anderen Bundesländern  
logo: "https://heilpraktiker-physiotherapie.com/assets/images/LogoHPPT.svg"
logo600jpg: "https://heilpraktiker-physiotherapie.com/assets/images/LogoHPPT600.jpg"
Bannerjpg: "https://heilpraktiker-physiotherapie.com/assets/images/BannerHPPT.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://heilpraktiker-physiotherapie.com" # the base hostname & protocol for your site
repository: heilpraktiker-physiotherapie/heilpraktiker-physiotherapie.github.io

paginate:	10 # The number of posts to show per page on your homepage
paginate_path: '/neuigkeiten-und-lesenswertes-zum-heilpraktiker-physiotherapie/page:num/'

name: 'Arne Brödel'
bio: Physiotherapeut, Heilpraktiker (Physiotherapie)
author_image: "https//heilpraktiker-physiotherapie.com/assets/images/author.jpg"
twitter_username: PhysioHP
twitter_url: https://twitter.com/PhysioHP
facebook_url: https://www.facebook.com/HeilpraktikerPhysiotherapie/
googleplus_url: https://plus.google.com/+Heilpraktikerphysiotherapiecom
youtube_url: https://www.youtube.com/c/Heilpraktikerphysiotherapiecom

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true
  auto_ids: false
  
#permalink: /neuigkeiten-und-lesenswertes-zum-heilpraktiker-physiotherapie/:title


plugins:
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-redirect-from

github: [metadata]