# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sektoraler Heilpraktiker für Physiotherapie - Fortbildung und Prüfung
email: info@heilpraktiker-physiotherapie.com    
description: >
  Awesome site description here
logo: "/assets/images/logosvg.svg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://heilpraktiker-physiotherapie.github.io" # the base hostname & protocol for your site
repository: heilpraktiker-physiotherapie/heilpraktiker-physiotherapie.github.io

paginate:	2 # The number of posts to show per page on your homepage
paginate_path: '/blog/page:num/'

name: 'Arne Brödel'
bio: >
  Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
  Ne solet nostrum complectitur pri, vis ut inani populo.
author_image: "/assets/images/author.jpg"
twitter_username: PhysioHP
twitter_url: https://twitter.com/PhysioHP
facebook_url: https://www.facebook.com/HeilpraktikerPhysiotherapie/
googleplus_url: https://plus.google.com/+Heilpraktikerphysiotherapiecom
youtube_url: https://www.youtube.com/c/Heilpraktikerphysiotherapiecom

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true
  
#permalink: /blog/:title


gems:
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-sitemap
  
